services:
  - type: web
    name: joshua-center-job-apps
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLIENT_URL
        fromService:
          type: web
          name: joshua-center-job-apps
          property: url
      - key: SERVER_URL
        fromService:
          type: web
          name: joshua-center-job-apps
          property: url