-- Additional 30 sample applicants for the database
-- This builds on the essential_data.sql entries

INSERT OR IGNORE INTO Applicant (
  email, name, address, city, state, zip, phone, 
  us_citizen, felony_conviction, felony_explanation, 
  dual_relationships, dual_relationships_explanation, 
  interests, why_joshua_center, ethical_framework_thoughts, 
  populations, education, previous_employer, 
  previous_employer_address, previous_employer_city, 
  previous_employer_state, previous_employer_zip, 
  previous_employer_phone, previous_employer_title, 
  previous_employer_length, previous_employer_reason_leaving, 
  other_employment, languages, gender, race_ethnicity, 
  resume_path, application_status
) VALUES 
-- Applicant 4
('emily.davis@example.com', 'Emily Davis', '333 Birch Rd', 'Rogers', 'AR', '72756', '(555) 456-7890',
 1, 0, NULL,
 'no', NULL,
 'EMDR, Trauma-focused therapy, Dialectical Behavior Therapy',
 'The Joshua Center''s commitment to underserved populations resonates with my professional goals.',
 'Ethical practice means considering social justice implications and advocating for clients'' best interests.',
 '["LGBTQ+", "Trauma Survivors", "Anxiety/Depression"]',
 'Master''s in Social Work from University of Arkansas (2017)',
 'Crisis Intervention Center',
 '444 Walnut Ave', 'Fayetteville', 'AR', '72701',
 '(555) 654-3210', 'Clinical Social Worker',
 '4 years', 'Seeking more aligned clinical approach',
 NULL, 'English', 'Female', 'White/Caucasian',
 '/uploads/sample-resume-4.pdf', 'rejected'),

-- Applicant 5
('david.brown@example.com', 'David Brown', '777 Spruce St', 'Siloam Springs', 'AR', '72761', '(555) 567-8901',
 1, 1, 'This was a non-violent offense from 15 years ago. I completed all requirements and have maintained a clean record since.',
 'no', NULL,
 'Substance abuse recovery, Acceptance and Commitment Therapy, Cognitive Behavioral Therapy',
 'I am drawn to the Joshua Center''s evidence-based practices and would like to contribute to your addiction recovery programs.',
 'I believe in transparency and honesty in the therapeutic relationship while maintaining appropriate boundaries.',
 '["Adults", "Addiction Recovery", "Groups"]',
 'Master''s in Counseling Psychology from University of Oklahoma (2010)',
 'Addiction Treatment Center',
 '888 Pine St', 'Tulsa', 'OK', '74103',
 '(555) 543-2109', 'Substance Abuse Counselor',
 '10 years', 'Desire to work with different populations',
 NULL, 'English', 'Male', 'Multiracial',
 '/uploads/sample-resume-5.pdf', 'not viewed'),

-- Applicant 6
('jennifer.miller@example.com', 'Jennifer Miller', '999 Aspen Dr', 'Conway', 'AR', '72032', '(555) 678-9012',
 1, 0, NULL,
 'no', NULL,
 'Child and adolescent development, Play therapy, Art therapy',
 'I value the Joshua Center''s focus on holistic care and would love to bring my expertise in child therapy.',
 'I am committed to child welfare and ensuring appropriate informed consent with minors and their guardians.',
 '["Children", "Adolescents", "Developmental Disabilities"]',
 'Master''s in Counseling from University of Central Arkansas (2016)',
 'School Counseling Office',
 '111 School St', 'Conway', 'AR', '72032',
 '(555) 432-1098', 'School Counselor',
 '5 years', 'Expanding professional skills',
 NULL, 'English', 'Female', 'White/Caucasian',
 '/uploads/sample-resume-6.pdf', 'in review'),

-- Applicant 7
('robert.taylor@example.com', 'Robert Taylor', '222 Cedar Ln', 'Jonesboro', 'AR', '72401', '(555) 789-0123',
 1, 0, NULL,
 'unsure', 'I believe I may know someone associated with the organization through mutual acquaintances.',
 'Trauma-focused therapy, EMDR, Crisis intervention',
 'The Joshua Center''s reputation for clinical excellence and trauma-informed care aligns with my professional focus.',
 'I prioritize trauma-informed care principles and creating a safe environment for clients to heal.',
 '["Veterans", "Trauma Survivors", "Adults"]',
 'Master''s in Clinical Mental Health from Arkansas State University (2014)',
 'Veterans Affairs Medical Center',
 '333 Veterans Way', 'Jonesboro', 'AR', '72401',
 '(555) 321-0987', 'Mental Health Therapist',
 '7 years', 'Seeking new challenges',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-7.pdf', 'not viewed'),

-- Applicant 8
('lisa.anderson@example.com', 'Lisa Anderson', '444 Maple Ave', 'Fayetteville', 'AR', '72701', '(555) 890-1234',
 1, 0, NULL,
 'no', NULL,
 'Cognitive Behavioral Therapy, Mindfulness-based interventions, Acceptance and Commitment Therapy',
 'I believe in the Joshua Center''s integrative approaches and want to contribute to your evidence-based programs.',
 'I am committed to ongoing professional development and supervision to ensure ethical practice.',
 '["Adults", "Anxiety/Depression", "LGBTQ+"]',
 'PhD in Clinical Psychology from University of Memphis (2018)',
 'Private Practice Group',
 '555 College Ave', 'Fayetteville', 'AR', '72701',
 '(555) 210-9876', 'Clinical Psychologist',
 '3 years', 'Desire to work with different populations',
 'Previously worked at University Counseling Services for 2 years.', 'English', 'Female', 'Asian',
 '/uploads/sample-resume-8.pdf', 'accepted'),

-- Applicant 9
('thomas.wilson@example.com', 'Thomas Wilson', '666 Oak St', 'Little Rock', 'AR', '72201', '(555) 901-2345',
 1, 0, NULL,
 'no', NULL,
 'Family systems, Solution-focused brief therapy, Integrative and holistic approaches',
 'The Joshua Center''s commitment to family-centered care matches my therapeutic approach.',
 'I believe in collaborative decision-making and ensuring client autonomy in the therapeutic process.',
 '["Families", "Couples", "Adults"]',
 'Master''s in Marriage and Family Therapy from Harding University (2015)',
 'Family Therapy Clinic',
 '777 Family Way', 'Little Rock', 'AR', '72201',
 '(555) 109-8765', 'Marriage and Family Therapist',
 '6 years', 'Relocation',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-9.pdf', 'not viewed'),

-- Applicant 10
('amanda.harris@example.com', 'Amanda Harris', '888 Pine Blvd', 'Rogers', 'AR', '72756', '(555) 012-3456',
 1, 0, NULL,
 'no', NULL,
 'Child and adolescent development, Play therapy, Trauma-focused therapy',
 'I am passionate about the Joshua Center''s work with underserved children and families.',
 'I prioritize child welfare and creating a trauma-informed environment for young clients.',
 '["Children", "Adolescents", "Trauma Survivors"]',
 'Master''s in Counseling from John Brown University (2019)',
 'Youth Services Agency',
 '999 Youth Dr', 'Rogers', 'AR', '72756',
 '(555) 098-7654', 'Child Therapist',
 '2 years', 'Expanding professional skills',
 NULL, 'English, Spanish', 'Female', 'Hispanic/Latino',
 '/uploads/sample-resume-10.pdf', 'in review'),

-- Applicant 11
('william.jackson@example.com', 'William Jackson', '101 Magnolia Ln', 'Springdale', 'AR', '72762', '(555) 123-4567',
 1, 0, NULL,
 'no', NULL,
 'Substance abuse treatment, Motivational interviewing, Cognitive Behavioral Therapy',
 'I admire the Joshua Center''s integrative approach to addiction treatment and recovery.',
 'I believe in meeting clients where they are and building on their intrinsic motivation for change.',
 '["Adults", "Addiction Recovery", "Groups"]',
 'Master''s in Clinical Mental Health Counseling from University of Arkansas (2017)',
 'Rehabilitation Facility',
 '202 Recovery Rd', 'Springdale', 'AR', '72762',
 '(555) 987-6543', 'Addiction Counselor',
 '4 years', 'Career advancement opportunity',
 NULL, 'English', 'Male', 'Black/African American',
 '/uploads/sample-resume-11.pdf', 'not viewed'),

-- Applicant 12
('rebecca.martinez@example.com', 'Rebecca Martinez', '303 River St', 'Fayetteville', 'AR', '72701', '(555) 234-5678',
 1, 0, NULL,
 'no', NULL,
 'Art therapy, Expressive arts, Trauma-focused interventions',
 'The Joshua Center''s holistic approach to healing aligns with my creative therapeutic methods.',
 'I believe in the healing power of creative expression and honoring each client''s unique path to wellness.',
 '["Children", "Adolescents", "Trauma Survivors"]',
 'Master''s in Art Therapy from Drexel University (2018)',
 'Community Mental Health Center',
 '404 Healing Way', 'Fayetteville', 'AR', '72701',
 '(555) 876-5432', 'Art Therapist',
 '3 years', 'Seeking more aligned clinical approach',
 NULL, 'English, Spanish', 'Female', 'Hispanic/Latino',
 '/uploads/sample-resume-12.pdf', 'in review'),

-- Applicant 13
('daniel.thompson@example.com', 'Daniel Thompson', '505 Lake View Dr', 'Bentonville', 'AR', '72712', '(555) 345-6789',
 1, 0, NULL,
 'no', NULL,
 'Cognitive processing therapy, Trauma-focused CBT, EMDR',
 'I am impressed by the Joshua Center''s commitment to evidence-based trauma treatment.',
 'I believe in empowering clients through education about trauma and recovery processes.',
 '["Adults", "Veterans", "Trauma Survivors"]',
 'PhD in Clinical Psychology from University of Missouri (2015)',
 'Veterans Affairs Medical Center',
 '606 Veterans Blvd', 'Fayetteville', 'AR', '72701',
 '(555) 765-4321', 'Clinical Psychologist',
 '6 years', 'Seeking new challenges',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-13.pdf', 'accepted'),

-- Applicant 14
('stephanie.lee@example.com', 'Stephanie Lee', '707 Mountain View Rd', 'Rogers', 'AR', '72756', '(555) 456-7890',
 1, 0, NULL,
 'no', NULL,
 'Family systems therapy, Emotionally focused therapy, Solution-focused brief therapy',
 'The Joshua Center''s emphasis on family healing and relationship work matches my clinical interests.',
 'I believe in the importance of attachment and secure bonds in healing relationship dynamics.',
 '["Couples", "Families", "Adults"]',
 'Master''s in Marriage and Family Therapy from John Brown University (2016)',
 'Private Practice Group',
 '808 Therapy Circle', 'Rogers', 'AR', '72756',
 '(555) 654-3210', 'Marriage and Family Therapist',
 '5 years', 'Expanding professional skills',
 NULL, 'English, Korean', 'Female', 'Asian',
 '/uploads/sample-resume-14.pdf', 'not viewed'),

-- Applicant 15
('christopher.white@example.com', 'Christopher White', '909 Forest Hills Ln', 'Fayetteville', 'AR', '72701', '(555) 567-8901',
 1, 0, NULL,
 'yes', 'I have a distant family connection to one of your staff members through church activities.',
 'Psychodynamic therapy, Attachment-based approaches, Interpersonal therapy',
 'I value the Joshua Center''s depth-oriented approach and attention to relationship patterns.',
 'I believe in the importance of the therapeutic relationship as a vehicle for healing and growth.',
 '["Adults", "Couples", "Anxiety/Depression"]',
 'PhD in Counseling Psychology from University of Arkansas (2014)',
 'University Counseling Services',
 '1010 Campus Dr', 'Fayetteville', 'AR', '72701',
 '(555) 543-2109', 'Counseling Psychologist',
 '7 years', 'Desire to work in community mental health',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-15.pdf', 'in review'),

-- Applicant 16
('nicole.garcia@example.com', 'Nicole Garcia', '111 Sunshine Ave', 'Springdale', 'AR', '72762', '(555) 678-9012',
 1, 0, NULL,
 'no', NULL,
 'Dialectical Behavior Therapy, Mindfulness-based interventions, Skills training',
 'I admire the Joshua Center''s structured approach to treatment for complex clients.',
 'I believe in balancing acceptance and change strategies while maintaining clear boundaries.',
 '["Adults", "Adolescents", "Anxiety/Depression"]',
 'Master''s in Clinical Mental Health Counseling from University of Arkansas (2018)',
 'Behavioral Health Services',
 '1212 Wellness Way', 'Springdale', 'AR', '72762',
 '(555) 432-1098', 'DBT Therapist',
 '3 years', 'Seeking new challenges',
 NULL, 'English, Spanish', 'Female', 'Hispanic/Latino',
 '/uploads/sample-resume-16.pdf', 'not viewed'),

-- Applicant 17
('james.rodriguez@example.com', 'James Rodriguez', '1313 Valley View Dr', 'Rogers', 'AR', '72756', '(555) 789-0123',
 1, 0, NULL,
 'no', NULL,
 'Psychoanalytic therapy, Depth psychology, Dream analysis',
 'The Joshua Center''s emphasis on deep transformational work aligns with my approach.',
 'I believe in honoring the unconscious and attending to symbolic material in therapy.',
 '["Adults", "Anxiety/Depression", "LGBTQ+"]',
 'PhD in Clinical Psychology from Pacifica Graduate Institute (2013)',
 'Private Practice Group',
 '1414 Insight Ln', 'Rogers', 'AR', '72756',
 '(555) 321-0987', 'Psychoanalytic Psychologist',
 '8 years', 'Desire to join a collaborative practice',
 NULL, 'English, Spanish', 'Male', 'Hispanic/Latino',
 '/uploads/sample-resume-17.pdf', 'rejected'),

-- Applicant 18
('michelle.nguyen@example.com', 'Michelle Nguyen', '1515 Highland Ave', 'Fayetteville', 'AR', '72701', '(555) 890-1234',
 1, 0, NULL,
 'no', NULL,
 'Cognitive Behavioral Therapy, Anxiety treatment, Exposure therapy',
 'I am impressed by the Joshua Center''s evidence-based approaches to anxiety disorders.',
 'I believe in empowering clients through skills development and behavioral experimentation.',
 '["Adults", "Adolescents", "Anxiety/Depression"]',
 'PhD in Clinical Psychology from University of Arkansas (2017)',
 'Anxiety Treatment Center',
 '1616 Calm Street', 'Fayetteville', 'AR', '72701',
 '(555) 210-9876', 'Clinical Psychologist',
 '4 years', 'Seeking a more diverse clinical environment',
 NULL, 'English, Vietnamese', 'Female', 'Asian',
 '/uploads/sample-resume-18.pdf', 'in review'),

-- Applicant 19
('anthony.scott@example.com', 'Anthony Scott', '1717 Oakwood Dr', 'Little Rock', 'AR', '72201', '(555) 901-2345',
 1, 0, NULL,
 'no', NULL,
 'Group therapy, Interpersonal process, Community mental health',
 'The Joshua Center''s commitment to accessible care matches my professional values.',
 'I believe in the healing power of group connection and shared experience.',
 '["Adults", "Groups", "Addiction Recovery"]',
 'Master''s in Clinical Social Work from University of Arkansas Little Rock (2015)',
 'Community Mental Health Center',
 '1818 Community Way', 'Little Rock', 'AR', '72201',
 '(555) 109-8765', 'Group Therapy Coordinator',
 '6 years', 'Relocation to Northwest Arkansas',
 NULL, 'English', 'Male', 'Black/African American',
 '/uploads/sample-resume-19.pdf', 'not viewed'),

-- Applicant 20
('katherine.robinson@example.com', 'Katherine Robinson', '1919 Cedar Point Rd', 'Bentonville', 'AR', '72712', '(555) 012-3456',
 1, 0, NULL,
 'no', NULL,
 'Gestalt therapy, Experiential approaches, Somatic experiencing',
 'I value the Joshua Center''s holistic view of mental health and embodied healing.',
 'I believe in the wisdom of the body and the integration of physical and emotional experience.',
 '["Adults", "Trauma Survivors", "Anxiety/Depression"]',
 'Master''s in Counseling Psychology from Naropa University (2016)',
 'Holistic Healing Center',
 '2020 Wellness Blvd', 'Bentonville', 'AR', '72712',
 '(555) 098-7654', 'Somatic Therapist',
 '5 years', 'Desire to join a like-minded practice',
 NULL, 'English', 'Female', 'White/Caucasian',
 '/uploads/sample-resume-20.pdf', 'not viewed'),

-- Applicant 21
('ryan.phillips@example.com', 'Ryan Phillips', '2121 River Bend Dr', 'Fayetteville', 'AR', '72701', '(555) 123-4567',
 1, 0, NULL,
 'no', NULL,
 'Rational Emotive Behavior Therapy, Cognitive approaches, Stress management',
 'The Joshua Center''s practical approach to mental health treatment resonates with me.',
 'I believe in helping clients develop rational thinking patterns and emotional resilience.',
 '["Adults", "Anxiety/Depression", "Groups"]',
 'Master''s in Counseling Psychology from University of Arkansas (2019)',
 'Employee Assistance Program',
 '2222 Corporate Pkwy', 'Fayetteville', 'AR', '72701',
 '(555) 987-6543', 'Staff Counselor',
 '2 years', 'Seeking broader clinical experience',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-21.pdf', 'not viewed'),

-- Applicant 22
('olivia.sanchez@example.com', 'Olivia Sanchez', '2323 Mountain Ridge Rd', 'Rogers', 'AR', '72756', '(555) 234-5678',
 1, 0, NULL,
 'no', NULL,
 'Narrative therapy, Multicultural counseling, Social justice advocacy',
 'I admire the Joshua Center''s commitment to serving diverse populations.',
 'I believe in honoring clients'' cultural contexts and personal narratives in the therapeutic process.',
 '["LGBTQ+", "Multicultural Populations", "Adolescents"]',
 'Master''s in Counseling from University of Arkansas (2017)',
 'LGBTQ+ Youth Center',
 '2424 Pride Ave', 'Rogers', 'AR', '72756',
 '(555) 876-5432', 'Multicultural Counselor',
 '4 years', 'Seeking a more inclusive clinical environment',
 NULL, 'English, Spanish', 'Female', 'Hispanic/Latino',
 '/uploads/sample-resume-22.pdf', 'in review'),

-- Applicant 23
('brian.walker@example.com', 'Brian Walker', '2525 Lakeshore Dr', 'Conway', 'AR', '72032', '(555) 345-6789',
 1, 0, NULL,
 'no', NULL,
 'Play therapy, Child-centered approaches, Parent coaching',
 'The Joshua Center''s family-focused care aligns with my specialized work with children.',
 'I believe in creating a safe, playful environment where children can process and heal.',
 '["Children", "Families", "Developmental Disabilities"]',
 'Master''s in Counseling with Play Therapy Certification from University of Central Arkansas (2018)',
 'Children''s Therapeutic Services',
 '2626 Playful Ln', 'Conway', 'AR', '72032',
 '(555) 765-4321', 'Registered Play Therapist',
 '3 years', 'Relocation to Northwest Arkansas',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-23.pdf', 'accepted'),

-- Applicant 24
('samantha.brooks@example.com', 'Samantha Brooks', '2727 Summit View Dr', 'Fayetteville', 'AR', '72701', '(555) 456-7890',
 1, 0, NULL,
 'unsure', 'I may have mutual connections with staff through professional networks.',
 'Acceptance and Commitment Therapy, Mindfulness-based approaches, Values work',
 'The Joshua Center''s emphasis on values-based living matches my therapeutic approach.',
 'I believe in helping clients build psychological flexibility while honoring their personal values.',
 '["Adults", "Anxiety/Depression", "Chronic Pain"]',
 'PhD in Clinical Psychology from University of Arkansas (2016)',
 'Pain Management Center',
 '2828 Wellness Way', 'Fayetteville', 'AR', '72701',
 '(555) 654-3210', 'Health Psychologist',
 '5 years', 'Seeking broader clinical applications',
 NULL, 'English', 'Female', 'White/Caucasian',
 '/uploads/sample-resume-24.pdf', 'not viewed'),

-- Applicant 25
('kevin.chen@example.com', 'Kevin Chen', '2929 Highland Park Dr', 'Bentonville', 'AR', '72712', '(555) 567-8901',
 1, 0, NULL,
 'no', NULL,
 'Integrative psychotherapy, Multicultural approaches, Cross-cultural counseling',
 'I value the Joshua Center''s commitment to serving diverse communities.',
 'I believe in honoring cultural differences and adapting therapeutic approaches accordingly.',
 '["Adults", "Multicultural Populations", "International Clients"]',
 'PhD in Counseling Psychology from University of Missouri (2015)',
 'International Student Services',
 '3030 Global Ave', 'Bentonville', 'AR', '72712',
 '(555) 543-2109', 'International Student Counselor',
 '6 years', 'Seeking community mental health position',
 NULL, 'English, Mandarin, Cantonese', 'Male', 'Asian',
 '/uploads/sample-resume-25.pdf', 'in review'),

-- Applicant 26
('rachel.patel@example.com', 'Rachel Patel', '3131 Meadow Lane', 'Rogers', 'AR', '72756', '(555) 678-9012',
 1, 0, NULL,
 'no', NULL,
 'Solution-focused brief therapy, Crisis intervention, Strength-based approaches',
 'The Joshua Center''s practical, results-oriented approach aligns with my clinical style.',
 'I believe in focusing on client strengths and rapid resolution of presenting concerns.',
 '["Adults", "Crisis Intervention", "Couples"]',
 'Master''s in Clinical Social Work from University of Arkansas (2017)',
 'Crisis Center',
 '3232 Emergency Way', 'Rogers', 'AR', '72756',
 '(555) 432-1098', 'Crisis Intervention Specialist',
 '4 years', 'Looking for a more stable clinical environment',
 NULL, 'English, Hindi', 'Female', 'Asian',
 '/uploads/sample-resume-26.pdf', 'not viewed'),

-- Applicant 27
('eric.gonzalez@example.com', 'Eric Gonzalez', '3333 Pine Valley Rd', 'Springdale', 'AR', '72762', '(555) 789-0123',
 1, 0, NULL,
 'no', NULL,
 'Motivational interviewing, Strength-based approaches, Substance abuse treatment',
 'I admire the Joshua Center''s integrated approach to substance use disorders.',
 'I believe in meeting clients where they are and building on their intrinsic motivation for change.',
 '["Adults", "Addiction Recovery", "Groups"]',
 'Master''s in Rehabilitation Counseling from University of Arkansas (2018)',
 'Substance Abuse Treatment Center',
 '3434 Recovery Rd', 'Springdale', 'AR', '72762',
 '(555) 321-0987', 'Substance Abuse Counselor',
 '3 years', 'Seeking a more collaborative team environment',
 NULL, 'English, Spanish', 'Male', 'Hispanic/Latino',
 '/uploads/sample-resume-27.pdf', 'in review'),

-- Applicant 28
('brittany.coleman@example.com', 'Brittany Coleman', '3535 Sunset Blvd', 'Fayetteville', 'AR', '72701', '(555) 890-1234',
 1, 1, 'I had a misdemeanor charge from 10 years ago related to a protest. All requirements were completed and my record has been clean since.',
 'no', NULL,
 'Social justice counseling, Advocacy, Multicultural approaches',
 'The Joshua Center''s commitment to underserved populations matches my professional values.',
 'I believe in addressing systemic barriers to mental health and advocating for marginalized communities.',
 '["LGBTQ+", "Multicultural Populations", "Youth"]',
 'Master''s in Social Work with Social Justice Concentration from University of Arkansas (2016)',
 'LGBTQ+ Resource Center',
 '3636 Rainbow Rd', 'Fayetteville', 'AR', '72701',
 '(555) 210-9876', 'Advocacy Coordinator and Counselor',
 '5 years', 'Seeking a more clinical role',
 NULL, 'English', 'Female', 'Black/African American',
 '/uploads/sample-resume-28.pdf', 'not viewed'),

-- Applicant 29
('marcus.washington@example.com', 'Marcus Washington', '3737 Oakwood Terrace', 'Little Rock', 'AR', '72201', '(555) 901-2345',
 1, 0, NULL,
 'no', NULL,
 'Cognitive Behavioral Therapy, Trauma-focused interventions, Veterans mental health',
 'The Joshua Center''s commitment to veterans'' mental health resonates with my professional focus.',
 'I believe in trauma-informed approaches that honor the unique experiences of military personnel.',
 '["Veterans", "Adults", "Trauma Survivors"]',
 'Master''s in Clinical Mental Health Counseling from University of Arkansas Little Rock (2014)',
 'Veterans Affairs Medical Center',
 '3838 Veterans Way', 'Little Rock', 'AR', '72201',
 '(555) 109-8765', 'Veterans Mental Health Specialist',
 '7 years', 'Relocation to Northwest Arkansas',
 NULL, 'English', 'Male', 'Black/African American',
 '/uploads/sample-resume-29.pdf', 'accepted'),

-- Applicant 30
('lindsay.morgan@example.com', 'Lindsay Morgan', '3939 Willow Creek Rd', 'Bentonville', 'AR', '72712', '(555) 012-3456',
 1, 0, NULL,
 'no', NULL,
 'Mindfulness-based stress reduction, Wellness coaching, Integrative mental health',
 'I value the Joshua Center''s holistic approach to wellness and mental health.',
 'I believe in addressing mind-body connections and promoting overall wellbeing.',
 '["Adults", "Groups", "Anxiety/Depression"]',
 'Master''s in Counseling Psychology with Mindfulness Certification from Naropa University (2017)',
 'Wellness Center',
 '4040 Harmony Way', 'Bentonville', 'AR', '72712',
 '(555) 098-7654', 'Mindfulness Coach and Therapist',
 '4 years', 'Seeking a more traditional mental health setting',
 NULL, 'English', 'Female', 'White/Caucasian',
 '/uploads/sample-resume-30.pdf', 'not viewed'),

-- Applicant 31
('jeremy.foster@example.com', 'Jeremy Foster', '4141 Mountain View Dr', 'Fayetteville', 'AR', '72701', '(555) 123-4567',
 1, 0, NULL,
 'no', NULL,
 'Existential therapy, Meaning-centered approaches, End-of-life counseling',
 'The Joshua Center''s depth-oriented approach aligns with my existential therapeutic focus.',
 'I believe in helping clients find meaning and purpose even in the face of suffering.',
 '["Adults", "Elderly", "Grief/Loss"]',
 'PhD in Counseling Psychology from University of Arkansas (2013)',
 'Hospice Services',
 '4242 Peaceful Way', 'Fayetteville', 'AR', '72701',
 '(555) 987-6543', 'Bereavement Counselor',
 '8 years', 'Seeking broader clinical applications',
 NULL, 'English', 'Male', 'White/Caucasian',
 '/uploads/sample-resume-31.pdf', 'in review'),

-- Applicant 32
('alicia.ramirez@example.com', 'Alicia Ramirez', '4343 Sunnydale Ln', 'Rogers', 'AR', '72756', '(555) 234-5678',
 1, 0, NULL,
 'no', NULL,
 'Culturally responsive therapy, Immigration issues, Trauma-focused care',
 'I admire the Joshua Center''s commitment to serving diverse and underserved populations.',
 'I believe in honoring cultural identity and providing culturally competent mental health care.',
 '["Multicultural Populations", "Immigrants", "Families"]',
 'Master''s in Social Work from University of Arkansas (2018)',
 'Immigrant Resource Center',
 '4444 Diversity Ave', 'Rogers', 'AR', '72756',
 '(555) 876-5432', 'Bilingual Therapist',
 '3 years', 'Seeking a more clinical mental health setting',
 NULL, 'English, Spanish', 'Female', 'Hispanic/Latino',
 '/uploads/sample-resume-32.pdf', 'not viewed'),

-- Applicant 33
('jason.kim@example.com', 'Jason Kim', '4545 Lakeside Dr', 'Bentonville', 'AR', '72712', '(555) 345-6789',
 1, 0, NULL,
 'no', NULL,
 'Cognitive Behavioral Therapy, Acceptance and Commitment Therapy, Cross-cultural counseling',
 'The Joshua Center''s evidence-based yet culturally sensitive approach matches my clinical style.',
 'I believe in balancing evidence-based protocols with cultural adaptations.',
 '["Adults", "Asian American Clients", "Anxiety/Depression"]',
 'PhD in Clinical Psychology from University of Washington (2016)',
 'University Counseling Center',
 '4646 Campus Dr', 'Bentonville', 'AR', '72712',
 '(555) 765-4321', 'Staff Psychologist',
 '5 years', 'Seeking community mental health position',
 NULL, 'English, Korean', 'Male', 'Asian',
 '/uploads/sample-resume-33.pdf', 'in review');

-- Create sample resume files in uploads directory
-- In a real scenario, these would be actual PDF files